version: "3.9"
services:
  app: # name of the first service
    image: zephtos/openbeefrontend:latest
    ports:
      - "8000:4200" # specify port forewarding
  backend: # name of the third service
    image: zephtos/MarketService:latest # specify image to build container from
    ports:
      - "44358:80" #specify ports forewarding
